package com.farjad.db.schema;

public enum DSAttributes {
    TRANSACTION_ID, PRODUCT_ID, CUSTOMER_ID, CUSTOMER_NAME, STORE_ID, STORE_NAME, T_DATE, QUANTITY,
    PRODUCT_NAME, SUPPLIER_ID, SUPPLIER_NAME, PRICE, TOTAL_SALE
}
