CREATE DATABASE IF NOT EXISTS DWH_PROJECT;
USE DWH_PROJECT;

-- DROP SCHEMA
DROP TABLE IF EXISTS STOREANALYSIS_MV;
DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS TIME_DIM;
DROP TABLE IF EXISTS STORES;
DROP TABLE IF EXISTS SUPPLIERS;
DROP TABLE IF EXISTS CUSTOMERS;

-- SCHEMA DEFINITION

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID VARCHAR(4) PRIMARY KEY NOT NULL,
    CUSTOMER_NAME VARCHAR(30)
);

CREATE TABLE SUPPLIERS(
    SUPPLIER_ID VARCHAR(5) PRIMARY KEY NOT NULL,
    SUPPLIER_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE STORES(
    STORE_ID VARCHAR(4) PRIMARY KEY NOT NULL,
    STORE_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE TIME_DIM(
    TIME_ID DATE PRIMARY KEY NOT NULL,
    DAY_NUM DECIMAL(2,0) NOT NULL CHECK(DAY_NUM >= 1 AND DAY_NUM <= 31),
    MONTH_NUM DECIMAL(2,0) NOT NULL CHECK(MONTH_NUM >= 1 AND MONTH_NUM <= 12),
    QTR_NUM DECIMAL(1,0) NOT NULL CHECK(QTR_NUM >= 1 AND QTR_NUM <= 4),
    YEAR_NUM DECIMAL(4,0) NOT NULL CHECK(YEAR_NUM >= 0),
    DAY_OF_WEEK VARCHAR(9) NOT NULL CHECK(DAY_OF_WEEK IN ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'))
);

CREATE TABLE PRODUCTS(
    PRODUCT_ID VARCHAR(6) PRIMARY KEY NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE SALES(
    TRANSACTION_ID VARCHAR(28) PRIMARY KEY NOT NULL,
    PRODUCT_ID VARCHAR(6) NOT NULL,
    CUSTOMER_ID VARCHAR(4) NOT NULL,
    STORE_ID VARCHAR(4) NOT NULL,
    TIME_ID DATE NOT NULL,
    SUPPLIER_ID VARCHAR(5) NOT NULL,
    QUANTITY DECIMAL(3,0) NOT NULL,
    TOTAL_SALE DECIMAL(7,2) NOT NULl,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
    FOREIGN KEY (TIME_ID) REFERENCES TIME_DIM(TIME_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);
